FROM oven/bun:1 AS dev

WORKDIR /usr/src/app
USER bun

COPY --chown=bun:bun package.json bun.lock ./
RUN bun install

RUN mkdir -p /usr/src/app/bun && chown -R bun:bun /usr/src/app

EXPOSE 3000

CMD ["bun", "run", "dev"]

